services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # In prod we usually DON'T expose the DB port publicly.
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - db
    # No bind-mounts, no --reload; uses the optimized multi-stage Dockerfile

volumes:
  pgdata:
