name: Secret scan
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: pipx install detect-secrets
      - name: Scan (compare against baseline)
        run: detect-secrets --version && detect-secrets scan --baseline .secrets.baseline --all-files
